### ISSUE TITLE
Set up events tracking

### ISSUE THREAD

**Issue by jstrothman** [greenriver/wri-wpsi#119]
WRI uses Google Tag Manager to send events tracking data to Google Analytics. 
This is an inventory of interactions we should intentionally track (i.e. those that are not automatically tracked by the basic script).

Some items can be set in GTM based on the css class or id (or a few other options). Others will need to be sent explicitly to the "dataLayer" through a scripted call in the site

**Require dataLayer push (see request details in comments)**
Note: These still need to be added by Jackie/Julie as tags in GTM once they've been added to the dataLayer
- [x] Create GA custom dimension for visitorType (so we can exclude Admin visits with a filter set by WRI)
- [x] Create variable, tag visitorType
- [x] Create variables selected country, region, sub-region
- [x] Figure out issue w/ selectedRegion coming through as message not event
- [x] Test tag for Map Click once selectedRegion is an event
- [x] Fix trigger for Map Search

**GTM-only**
- [x] External links (social separate from other sites)
- [x] Add Datasets button (opens modal)
- [x] Add|Remove Dataset button (adds to map)—want name of dataset and that it was added, or removed, from the modal
- [x] Modal tabs
- [x] Learn More from modal
- [x] Learn More from map page
- [x] Toggle: Highlight areas of water stress
- [x] Legend: Toggles & Info
- [x] Embedded video play (youtube, vimeo), timer
- [x] Category label links

**GTM-prefixed css class additions**
See comments below for detailed list of class addition requests. This gtm-prefixed classes will make the tracking more resilient to code changes. Currently many css classes are dynamically created. Also the 'gtm-' prefixing will act as a warning to developers that changes may break Google Tag Manager behavior, similar to when we use 'js-' prefixed classes to indicate javascript behavior tie-ins.
- [x] Edit GTM triggers that are not yet using ‘gtm-‘ prefixed classes

**GA Filters**
- [x] Don't track visits to heroku (uses different db—basically staging) [Kevin created GA filter to exclude hostname]
- [x] Don't track visits with visitorType admin [Kevin created filter]

**Dashboard**
- [x] Custom dash and set to send monthly
